// Soundsets
const int SOUNDSET_MALE_DESERT_WARRIOR = 30000;
const int SOUNDSET_FEMALE_IMPATIENT = 30001;
const int SOUNDSET_MALE_ARCHMAGE = 30002;
const int SOUNDSET_FEMALE_NOBLE_MYSTRA_WIZARD = 30003;
const int SOUNDSET_FEMALE_ADVENTURER_PALADIN_OF_MYSTRA = 30004;
const int SOUNDSET_MALE_ADVENTURER_CURIOUS_MAGE = 30005;
const int SOUNDSET_MALE_ADVENTURER_UTHGARDT_RED_TIGER_TRIBE_BARBARIAN = 30006;
const int SOUNDSET_MALE_ADVENTURER_UTHGARDT_RED_TIGER_TRIBE_BARBARIAN_SEASONED = 30007;

