// Spells
const int SPELL_BLINDING_SPITTLE = 30000;

// Feats
const int FEAT_EPIC_EYE_OF_GRUUMSH = 30001;
const int FEAT_EPIC_HARPER_SCOUT = 30002;
const int FEAT_EPIC_PURPLE_DRAGON_KNIGHT = 30003;
const int FEAT_EPIC_SHOU_DISCIPLE = 30004;
const int FEAT_FAVORED_ENEMY_OOZES = 30000;

// Soundsets
const int SOUNDSET_CAT_HOUSECAT = 30019;
const int SOUNDSET_FEMALE_ADVENTURER_BARD = 30013;
const int SOUNDSET_FEMALE_ADVENTURER_BARD_VETERAN = 30014;
const int SOUNDSET_FEMALE_ADVENTURER_EILISTRAEE_ASSASSIN = 30012;
const int SOUNDSET_FEMALE_ADVENTURER_ELVEN_CLERIC_OF_SEHANINE_MOONBOW = 30010;
const int SOUNDSET_FEMALE_ADVENTURER_ELVEN_CLERIC_OF_SEHANINE_MOONBOW_VETERAN = 30011;
const int SOUNDSET_FEMALE_ADVENTURER_PALADIN_OF_MYSTRA = 30004;
const int SOUNDSET_FEMALE_ADVENTURER_TOUGH_THIEF = 30008;
const int SOUNDSET_FEMALE_IMPATIENT = 30001;
const int SOUNDSET_FEMALE_NOBLE_MYSTRA_WIZARD = 30003;
const int SOUNDSET_MALE_ADVENTURER_BELLIGERENT_WIZARD = 30018;
const int SOUNDSET_MALE_ADVENTURER_COCKNEY_ROGUE = 30015;
const int SOUNDSET_MALE_ADVENTURER_COCKNEY_ROGUE_VETERAN = 30016;
const int SOUNDSET_MALE_ADVENTURER_CURIOUS_MAGE = 30005;
const int SOUNDSET_MALE_ADVENTURER_MONK_OF_THE_SILENT_LORD = 30009;
const int SOUNDSET_MALE_ADVENTURER_TIEFLING_FIGHTER = 30017;
const int SOUNDSET_MALE_ADVENTURER_UTHGARDT_RED_TIGER_TRIBE_BARBARIAN = 30006;
const int SOUNDSET_MALE_ADVENTURER_UTHGARDT_RED_TIGER_TRIBE_BARBARIAN_VETERAN = 30007;
const int SOUNDSET_MALE_ARCHMAGE = 30002;
const int SOUNDSET_MALE_DESERT_WARRIOR = 30000;

